spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb+srv://Abhijit:Password@activity-service.ianpcfo.mongodb.net/?appName=fitnessrecomendation
      database: fitnessrecomendation

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
